crum.hqbbq.web/Models/MenuItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace crum.hqbbq.web.Models
{
    public class MenuItem
    {
        public int ID { get; set; }

        [Display(Name = "Item")]
        [StringLength(60,MinimumLength =3)]
        [Required]
        public string Name { get; set; }

        [Required]
        [DataType(DataType.Currency)]
        public decimal Price { get; set; }
    }
}

crum.hqbbq.web/Models/SendMsgViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace crum.hqbbq.web.ViewModels
{
    public class SendMsgViewModel
    {
        public string Name {get; set;}
        public string Email {get; set;}
        public string Message {get; set;}
    }
}

crum.hqbbq.web/ViewModels/CreateMenuItemViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace crum.hqbbq.web.ViewModels
{
    public class CreateMenuItemViewModel
    {
        public string Name { get; set; }
        public string Price { get; set; }
    }
}

crum.hqbbq.web/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using crum.hqbbq.web.ViewModels;
public class ContactController : Controller
{
    public IActionResult Index()
        {
            SendMsgViewModel msg = new SendMsgViewModel();
            return View(msg);
        }

    [HttpPost]
    public IActionResult SendMsg(SendMsgViewModel msg)
    {
        if(ModelState.IsValid)
        {
            @ViewBag.Feedback = "<div class=\"notification is-success\">Message Received!</div><br>";
        }
        else
        {
            @ViewBag.Feedback = "<div class=\"notification is-danger\">Error encountered during transmission. Please try again.</div><br>";
        }

        return View("Index");
    }
}

crum.hqbbq.web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace crum.hqbbq.web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

crum.hqbbq.web/Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;
using crum.hqbbq.web.Data;
using crum.hqbbq.web.Models;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using System;
using crum.hqbbq.web.ViewModels;

public class MenuController : Controller
{
    private readonly MenuContext _context;

    public MenuController(MenuContext context)
    {
        _context = context;
    }

    public async Task<IActionResult> Index()
    {
        return View(await _context.MenuItems.ToListAsync());
    }

    /*
     * 
     *  Add Methods for changing the value of an item in the database
     *  
     */
    public IActionResult Add()
    {
        var item = new CreateMenuItemViewModel();
        return View(item);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Add([Bind("ID,Name,Price")] MenuItem item)
    {
        if (ModelState.IsValid)
        {
            var newItem = item;
            try
            {
                _context.Add(item);
                await _context.SaveChangesAsync();
            } catch (DbUpdateException ex)
            {
                throw new InvalidOperationException(string.Format("The object could not be added. Make sure that a " + "product with a product number '{0}' does not aleady exist.\n", item.Name), ex);
            }

            return RedirectToAction("Index");
        }
        return View();
    }

    /*
     * 
     *  Edit Methods for changing the value of an item in the database
     *  
     */

    public async Task<IActionResult> Edit(int? id)
    {
        if(id == null)
        {
            return NotFound();
        }

        MenuItem item = await _context.MenuItems.SingleOrDefaultAsync(m => m.ID == id);

        if (item == null)
        {
            return NotFound();
        }

        return View(item);
        
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Price")] MenuItem item)
    {
        if (id != item.ID)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(item);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (_context.MenuItems.Find(id) == null)
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("Index");
        }
        return View();
    }

    /*
     * 
     *  Delete Methods for changing the value of an item in the database
     *  
     */

    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var item = await _context.MenuItems
            .SingleOrDefaultAsync(m => m.ID == id);
        if (item == null)
        {
            return NotFound();
        }

        return View(item);
    }

    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var item = await _context.MenuItems.SingleOrDefaultAsync(m => m.ID == id);
        _context.MenuItems.Remove(item);
        await _context.SaveChangesAsync();
        return RedirectToAction("Index");
    }

    //Clean up of database connection
    private bool _disposed = false;

    protected override void Dispose(bool disposing)
    {
        if (_disposed)
            return;

        if(disposing)
        {
            _context.Dispose();
        }

        _disposed = true;

        base.Dispose(disposing);
    }
}

crum.hqbbq.web/Views/Contact/Index.cshtml
@model crum.hqbbq.web.ViewModels.SendMsgViewModel
@{
    ViewData["Title"] = "Contact";
}

<div class="container">
    
    
    <div class="columns">
        <div class="column is-half-desktop is-offset-one-quarter-desktop">
            <h2 class="title">@ViewData["Title"]</h2>

            @Html.Raw(ViewBag.Feedback)

            <p>
                We always love to hear from our customers and want to know what you like about our food or what we could do different. Have a favorite dish? Wish we had something you don't see? Let us know!
            </p>
            
            <form asp-controller="Contact" asp-action="SendMsg" method="post">
                <div class="field">
                    <label asp-for="Name" class="label">Name:</label>
                    <p class="control">
                        <input asp-for="Name" class="input">
                    </p>
                </div>
                <div class="field">
                    <label asp-for="Email" class="label">E-mail:</label>
                        <p class="control has-icons-left">
                            <input asp-for="Email" class="input">
                            <span class="icon is-small is-left"><i class="fa fa-envelope"></i></span>
                        </p>
                </div>
                <div class="field">
                    <label asp-for="Message" class="label">Message</label>
                    <p class="control">
                        <textarea asp-for="Message" class="textarea" placeholder="Textarea"></textarea>
                    </p>
                </div>
                <div class="field is-grouped">
                    <p class="control">
                        <button class="button">Submit</button>
                    </p>
                    <p class="control">
                        <button class="button is-link">Cancel</button>
                    </p>
                </div>
            </form>
        </div>
    </div>
</div>

crum.hqbbq.web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}
<div class="container">
    <div class="columns">
        <div class="column is-half-desktop is-offset-one-quarter-desktop">
            <h2 class="title">@ViewData["Title"]</h2>
            <h3>@ViewData["Message"]</h3>
            <br>
            <p>
                Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?
            </p>
        </div>
    </div>
</div>

crum.hqbbq.web/Views/Index.cshtml
@model crum.hqbbq.web.Models.MenuItem

<div class="container">
    <div class="columns is-desktop">
        <div class="column is-half-desktop is-offset-one-quarter-desktop">
            <h2 class="title">@ViewData["Title"]</h2>

            <form asp-controller="Menu" asp-action="Edit" method="post">
                <input type="hidden" asp-for="ID" />
                <div class="field">
                    <label asp-for="Name" class="label">Name:</label>
                    <p class="control">
                        <input asp-for="Name" class="input">
                    </p>
                </div>
                <div class="field">
                    <label asp-for="Price" class="label">Price:</label>
                    <p class="control">
                        <input asp-for="Price" class="input">
                    </p>
                </div>
                <div class="field is-grouped">
                    <p class="control">
                        <button class="button">Submit</button>
                    </p>
                    <p class="control">
                        <button class="button is-link">Cancel</button>
                    </p>
                </div>
            </form>
        </div>
    </div>
</div>

crum.hqbbq.web/Views/Menu/Add.cshtml
@model crum.hqbbq.web.ViewModels.CreateMenuItemViewModel

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    ViewData["Title"] = "Add Menu Item";
}

<div class="container">
    <div class="columns is-desktop">
        <div class="column is-half-desktop is-offset-one-quarter-desktop">
            <h2 class="title">@ViewData["Title"]</h2>

            <form asp-controller="Menu" asp-action="Add" method="post">
                <div class="field">
                    <label asp-for="Name" class="label">Name:</label>
                    <p class="control">
                        <input asp-for="Name" class="input">
                    </p>
                </div>
                <div class="field">
                    <label asp-for="Price" class="label">Price:</label>
                    <p class="control">
                        <input asp-for="Price" class="input">
                    </p>
                </div>
                <div class="field is-grouped">
                    <p class="control">
                        <button class="button is-success">Submit</button>
                    </p>
                    <p class="control">
                        <button class="button is-link">Cancel</button>
                    </p>
                </div>
            </form>
        </div>
    </div>
</div>

crum.hqbbq.web/Views/Menu/Delete.cshtml
@model crum.hqbbq.web.Models.MenuItem

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    ViewData["Title"] = "Delete Menu Item";
}

<div class="container">
    <div class="columns is-desktop">
        <div class="column is-half-desktop is-offset-one-quarter-desktop">
            <h2 class="title">@ViewData["Title"]</h2>

            <form asp-controller="Menu" asp-action="Delete" method="post">
                <input type="hidden" asp-for="ID" />
                <div class="field">
                    <label asp-for="Name" class="label">Name:</label>
                    <p class="control">
                        <input asp-for="Name" class="input">
                    </p>
                </div>
                <div class="field">
                    <label asp-for="Price" class="label">Price:</label>
                    <p class="control">
                        <input asp-for="Price" class="input">
                    </p>
                </div>
                <div class="field is-grouped">
                    <p class="control">
                        <button class="button is-danger">Submit</button>
                    </p>
                    <p class="control">
                        <button class="button is-link">Cancel</button>
                    </p>
                </div>
            </form>
        </div>
    </div>
</div>

crum.hqbbq.web/Views/Menu/Edit.cshtml
@model crum.hqbbq.web.Models.MenuItem

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    ViewData["Title"] = "Edit Menu Item";
}

<div class="container">
    <div class="columns is-desktop">
        <div class="column is-half-desktop is-offset-one-quarter-desktop">
            <h2 class="title">@ViewData["Title"]</h2>

            <form asp-controller="Menu" asp-action="Edit" method="post">
                <input type="hidden" asp-for="ID" />
                <div class="field">
                    <label asp-for="Name" class="label">Name:</label>
                    <p class="control">
                        <input asp-for="Name" class="input">
                    </p>
                </div>
                <div class="field">
                    <label asp-for="Price" class="label">Price:</label>
                    <p class="control">
                        <input asp-for="Price" class="input">
                    </p>
                </div>
                <div class="field is-grouped">
                    <p class="control">
                        <button class="button">Submit</button>
                    </p>
                    <p class="control">
                        <button class="button is-link">Cancel</button>
                    </p>
                </div>
            </form>
        </div>
    </div>
</div>

crum.hqbbq.web/Views/Menu/Index.cshtml
@model IEnumerable<crum.hqbbq.web.Models.MenuItem>

@{
    ViewData["Title"] = "Menu";
}

<div class="container">
    
    <div class="columns is-desktop">
        <div class="column is-half-desktop is-offset-one-quarter-desktop">
            <h2 class="title">@ViewData["Title"]</h2>
            <table class="table is-striped">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(m => m.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.Price)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(m => item.Name)</td>
                            <td class="has-text-right">@Html.DisplayFor(m => item.Price)</td>
                            <td class="has-text-centered">
                                <a asp-action="Edit" asp-route-id="@item.ID" class="button is-warning">Edit</a>
                                <a asp-action="Delete" asp-route-id="@item.ID" class="button is-danger">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="3" class="has-text-centered"><a asp-action="Add" class="button is-success">Add Menu Item</a></td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

crum.hqbbq.web/Views/Menu/_MenuForm.cshtml
@model crum.hqbbq.web.Models.MenuItem

<div class="container">
    <div class="columns is-desktop">
        <div class="column is-half-desktop is-offset-one-quarter-desktop">
            <h2 class="title">@ViewData["Title"]</h2>

            <form asp-controller="Menu" asp-action="Edit" method="post">
                <input type="hidden" asp-for="ID" />
                <div class="field">
                    <label asp-for="Name" class="label">Name:</label>
                    <p class="control">
                        <input asp-for="Name" class="input">
                    </p>
                </div>
                <div class="field">
                    <label asp-for="Price" class="label">Price:</label>
                    <p class="control">
                        <input asp-for="Price" class="input">
                    </p>
                </div>
                <div class="field is-grouped">
                    <p class="control">
                        <button class="button">Submit</button>
                    </p>
                    <p class="control">
                        <button class="button is-link">Cancel</button>
                    </p>
                </div>
            </form>
        </div>
    </div>
</div>

crum.hqbbq.web/Views/Shared/DisplayTemplates/decimal.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model decimal

@{
    IFormatProvider formatProvider =
        new System.Globalization.CultureInfo("en-US");
    <span class="currency">@Model.ToString("C", formatProvider)</span>
}

crum.hqbbq.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HQ BBQ</title>
    <environment names="Development">
        <link rel="stylesheet" href="~/css/bulma.css" />
        <link rel="stylesheet" href="~/css/font-awesome.min.css">
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/css/bulma.css" />
        <link rel="stylesheet" href="~/css/font-awesome.min.css">
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <section class="section">
        <!--Header Section-->
        <div class="hero">
            <div class="hero-head">
                <img class="logo" src="~/images/hqbbq_logo.jpg" alt="HQ BBQ Logo" />
            </div>
            <div class="hero-foot">
                <!-- Navigation goes here -->
                <nav id="nav" class="tabs is-centered">
                    <ul>
                        <li><a asp-controller="Home" asp-action="Index">About</a></li>
                        <li><a asp-controller="Menu" asp-action="Index">Menu</a></li>
                        <li><a asp-controller="Contact" asp-action="Index">Contact</a></li>
                    </ul>
                </nav>
            </div>
        </div>
        <!--End Navigation-->
        <!--End Header-->
        <!--Body Section rendered from the view-->
        @RenderBody()
    </section>
    <footer class="footer">
        <div class="container">
            <div class="columns">
                <div class="column is-half-desktop is-offset-one-quarter-desktop">
                    <div class="content has-text-centered">
                        <p>
                            <strong>HQ BBQ Website</strong> by <a href="#">Nathan Crum</a>. The source code is licensed
                            <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
                            is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC ANS 4.0</a>.
                        </p>
                        <p>
                            <a class="icon" href="https://github.com/jgthms/bulma">
                                <i class="fa fa-github"></i>
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <environment names="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("scripts", required: false)
</body>
</html>